version: '3.8'
services:
  php:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: php-container
    volumes:
      - ./backend:/var/www/html
    expose:
      - "9000"
    networks:
      - my_network

  postgres:
    image: postgres:13.14-bullseye
    container_name: postgres-container
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    networks:
      - my_network

  nginx:
    image: nginx:alpine
    container_name: nginx-container
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
      - ./backend:/var/www/html
    ports:
      - "8080:80"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
